@startuml
interface Observer

Subject -right-> Observer
Subject : + attach(subject)
Subject : + detach(subject)
Subject : + notify()

Observer : +update(subject)
ConcreteObserver ..|> Observer
ConcreteObserver : + update(subject)
@enduml